In [1]:
# import libraries
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split

print(tf.__version__)

2.2.0

In [2]:
data = pd.read_csv('train_data.csv')
dataT = pd.read_csv('test_data.csv')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29020 entries, 0 to 29019
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   BookingID                29020 non-null  int64
 1   LeadTime                 29020 non-null  int64
 2   ArrivalYear              29020 non-null  int64
 3   ArrivalMonth             29020 non-null  int64
 4   ArrivalDate              29020 non-null  int64
 5   NumWeekendNights         29020 non-null  int64
 6   NumWeekNights            29020 non-null  int64
 7   MealPlan                 29020 non-null  object
 8   Parking                  29020 non-null  int64
 9   RoomType                 29020 non-null  object
 10  NumAdults                29020 non-null  int64
 11  NumChildren              29020 non-null  int64
 12  MarketSegment            29020 non-null  object
 13  RepeatedGuest            29020 non-null  int64
 14  NumPrevCancellations     29020 non-null  int64
 15  NumPreviousNonCancelled  29020 non-null  int64
 16  AvgRoomPrice             29020 non-null  float64
 17  SpecialRequests          29020 non-null  int64
 18  BookingStatus            29020 non-null  object
dtypes: float64(1), int64(14), object(4)
memory usage: 4.2+ MB

In [3]:
data['MealPlan'] = pd.factorize(data.MealPlan)[0]
data['RoomType'] = pd.factorize(data.RoomType)[0]
data['MarketSegment'] = pd.factorize(data.MarketSegment)[0]
data['BookingStatus'] = pd.factorize(data.BookingStatus)[0]

dataT['MealPlan'] = pd.factorize(dataT.MealPlan)[0]
dataT['RoomType'] = pd.factorize(dataT.RoomType)[0]
dataT['MarketSegment'] = pd.factorize(dataT.MarketSegment)[0]
dataT['BookingStatus'] = pd.factorize(dataT.BookingStatus)[0]

data

,BookingID,LeadTime,ArrivalYear,ArrivalMonth,ArrivalDate,NumWeekendNights,NumWeekNights,MealPlan,Parking,RoomType,NumAdults,NumChildren,MarketSegment,RepeatedGuest,NumPrevCancellations,NumPreviousNonCancelled,AvgRoomPrice,SpecialRequests,BookingStatus
0,1,10,2018,3,31,0,1,0,0,0,1,0,0,0,0,0,95.00,0,0
1,2,116,2018,2,28,2,1,0,0,0,1,0,1,0,0,0,61.00,0,0
2,3,11,2018,7,25,1,2,0,0,0,2,1,1,0,0,0,129.75,1,1
3,4,3,2017,9,12,0,1,0,0,0,2,0,1,0,0,0,152.00,3,1
4,5,28,2018,3,7,1,3,0,0,0,2,0,2,0,0,0,87.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29015,29016,2,2018,11,21,1,2,0,0,0,1,0,1,0,0,0,100.67,1,1
29016,29017,18,2018,4,12,0,2,2,0,0,2,0,1,0,0,0,119.00,1,1
29017,29018,8,2017,9,29,0,3,0,0,0,1,0,0,0,0,0,65.00,0,1
29018,29019,20,2018,9,18,2,2,0,0,0,1,0,2,0,0,0,90.00,0,0
29019,29020,274,2018,7,31,2,1,0,0,3,2,0,1,0,0,0,96.50,1,1

In [4]:
features = ['LeadTime', 'ArrivalYear', 'ArrivalMonth', 'ArrivalDate', 'NumWeekendNights', 
            'NumWeekNights', 'MealPlan', 'Parking', 'RoomType', 'NumAdults', 'NumChildren', 
            'MarketSegment', 'RepeatedGuest', 'NumPrevCancellations', 'NumPreviousNonCancelled', 
            'AvgRoomPrice', 'SpecialRequests']
target = 'BookingStatus'

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# model = LogisticRegression()
X_train, X_test, y_train, y_test = train_test_split(data[features], data[target], test_size=0.2, random_state=24)

X_train

,LeadTime,ArrivalYear,ArrivalMonth,ArrivalDate,NumWeekendNights,NumWeekNights,MealPlan,Parking,RoomType,NumAdults,NumChildren,MarketSegment,RepeatedGuest,NumPrevCancellations,NumPreviousNonCancelled,AvgRoomPrice,SpecialRequests
12685,55,2017,11,10,0,1,0,0,0,1,0,1,0,0,0,73.80,2
18332,34,2018,9,2,0,1,2,0,0,2,0,1,0,0,0,99.00,1
25208,50,2018,3,21,1,3,0,0,0,2,0,1,0,0,0,93.50,1
26777,265,2018,6,24,0,2,1,0,0,2,0,2,0,0,0,115.00,1
6738,13,2018,3,20,1,0,0,0,0,2,0,2,0,0,0,85.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19857,205,2018,9,5,1,2,0,0,0,2,0,1,0,0,0,126.90,2
24919,21,2017,8,31,1,3,0,0,0,1,0,1,0,0,0,91.25,1
14528,54,2018,3,2,0,2,0,0,0,2,0,1,0,0,0,87.30,0
899,6,2018,4,22,2,3,0,0,0,1,2,1,0,0,0,104.92,1
12706,294,2018,10,23,2,3,0,0,2,2,0,1,0,0,0,76.58,1

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [7]:
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

Epoch 1/50
581/581 [==============================] - 1s 2ms/step - loss: 0.4731 - accuracy: 0.7747 - val_loss: 0.4119 - val_accuracy: 0.8075
Epoch 2/50
581/581 [==============================] - 1s 1ms/step - loss: 0.4254 - accuracy: 0.8045 - val_loss: 0.4000 - val_accuracy: 0.8176
Epoch 3/50
581/581 [==============================] - 1s 1ms/step - loss: 0.4123 - accuracy: 0.8171 - val_loss: 0.3895 - val_accuracy: 0.8193
Epoch 4/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3999 - accuracy: 0.8196 - val_loss: 0.3851 - val_accuracy: 0.8228
Epoch 5/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3972 - accuracy: 0.8224 - val_loss: 0.3798 - val_accuracy: 0.8258
Epoch 6/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3903 - accuracy: 0.8237 - val_loss: 0.3730 - val_accuracy: 0.8333
Epoch 7/50
581/581 [==============================] - 1s 2ms/step - loss: 0.3854 - accuracy: 0.8290 - val_loss: 0.3684 - val_accuracy: 0.8361
Epoch 8/50
581/581 [==============================] - 1s 2ms/step - loss: 0.3809 - accuracy: 0.8288 - val_loss: 0.3646 - val_accuracy: 0.8333
Epoch 9/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3773 - accuracy: 0.8307 - val_loss: 0.3628 - val_accuracy: 0.8411
Epoch 10/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3761 - accuracy: 0.8348 - val_loss: 0.3573 - val_accuracy: 0.8385
Epoch 11/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3737 - accuracy: 0.8340 - val_loss: 0.3563 - val_accuracy: 0.8426
Epoch 12/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3669 - accuracy: 0.8371 - val_loss: 0.3519 - val_accuracy: 0.8428
Epoch 13/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3656 - accuracy: 0.8395 - val_loss: 0.3508 - val_accuracy: 0.8471
Epoch 14/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3631 - accuracy: 0.8394 - val_loss: 0.3466 - val_accuracy: 0.8478
Epoch 15/50
581/581 [==============================] - 1s 2ms/step - loss: 0.3622 - accuracy: 0.8406 - val_loss: 0.3445 - val_accuracy: 0.8491
Epoch 16/50
581/581 [==============================] - 1s 2ms/step - loss: 0.3616 - accuracy: 0.8407 - val_loss: 0.3430 - val_accuracy: 0.8456
Epoch 17/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3565 - accuracy: 0.8396 - val_loss: 0.3421 - val_accuracy: 0.8484
Epoch 18/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3548 - accuracy: 0.8438 - val_loss: 0.3399 - val_accuracy: 0.8503
Epoch 19/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3551 - accuracy: 0.8443 - val_loss: 0.3375 - val_accuracy: 0.8506
Epoch 20/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3535 - accuracy: 0.8469 - val_loss: 0.3350 - val_accuracy: 0.8540
Epoch 21/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3523 - accuracy: 0.8439 - val_loss: 0.3390 - val_accuracy: 0.8521
Epoch 22/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3494 - accuracy: 0.8461 - val_loss: 0.3331 - val_accuracy: 0.8572
Epoch 23/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3504 - accuracy: 0.8454 - val_loss: 0.3332 - val_accuracy: 0.8557
Epoch 24/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3448 - accuracy: 0.8474 - val_loss: 0.3323 - val_accuracy: 0.8581
Epoch 25/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3461 - accuracy: 0.8493 - val_loss: 0.3328 - val_accuracy: 0.8577
Epoch 26/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3450 - accuracy: 0.8485 - val_loss: 0.3317 - val_accuracy: 0.8529
Epoch 27/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3450 - accuracy: 0.8484 - val_loss: 0.3278 - val_accuracy: 0.8592
Epoch 28/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3418 - accuracy: 0.8489 - val_loss: 0.3316 - val_accuracy: 0.8562
Epoch 29/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3430 - accuracy: 0.8497 - val_loss: 0.3294 - val_accuracy: 0.8581
Epoch 30/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3432 - accuracy: 0.8504 - val_loss: 0.3251 - val_accuracy: 0.8602
Epoch 31/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3416 - accuracy: 0.8471 - val_loss: 0.3291 - val_accuracy: 0.8557
Epoch 32/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3384 - accuracy: 0.8506 - val_loss: 0.3271 - val_accuracy: 0.8611
Epoch 33/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3398 - accuracy: 0.8531 - val_loss: 0.3284 - val_accuracy: 0.8607
Epoch 34/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3380 - accuracy: 0.8510 - val_loss: 0.3286 - val_accuracy: 0.8596
Epoch 35/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3357 - accuracy: 0.8551 - val_loss: 0.3266 - val_accuracy: 0.8615
Epoch 36/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3359 - accuracy: 0.8544 - val_loss: 0.3254 - val_accuracy: 0.8594
Epoch 37/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3340 - accuracy: 0.8525 - val_loss: 0.3247 - val_accuracy: 0.8671
Epoch 38/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3343 - accuracy: 0.8517 - val_loss: 0.3213 - val_accuracy: 0.8643
Epoch 39/50
581/581 [==============================] - 1s 2ms/step - loss: 0.3368 - accuracy: 0.8506 - val_loss: 0.3231 - val_accuracy: 0.8680
Epoch 40/50
581/581 [==============================] - 1s 2ms/step - loss: 0.3300 - accuracy: 0.8534 - val_loss: 0.3242 - val_accuracy: 0.8652
Epoch 41/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3339 - accuracy: 0.8533 - val_loss: 0.3250 - val_accuracy: 0.8656
Epoch 42/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3309 - accuracy: 0.8569 - val_loss: 0.3250 - val_accuracy: 0.8598
Epoch 43/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3335 - accuracy: 0.8535 - val_loss: 0.3276 - val_accuracy: 0.8594
Epoch 44/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3312 - accuracy: 0.8549 - val_loss: 0.3202 - val_accuracy: 0.8680
Epoch 45/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3314 - accuracy: 0.8556 - val_loss: 0.3277 - val_accuracy: 0.8633
Epoch 46/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3298 - accuracy: 0.8531 - val_loss: 0.3200 - val_accuracy: 0.8665s: 0.3303 - accuracy:
Epoch 47/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3314 - accuracy: 0.8567 - val_loss: 0.3194 - val_accuracy: 0.8650
Epoch 48/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3308 - accuracy: 0.8530 - val_loss: 0.3205 - val_accuracy: 0.8637
Epoch 49/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3301 - accuracy: 0.8571 - val_loss: 0.3224 - val_accuracy: 0.8680
Epoch 50/50
581/581 [==============================] - 1s 1ms/step - loss: 0.3263 - accuracy: 0.8569 - val_loss: 0.3204 - val_accuracy: 0.8734

In [8]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print('Test loss:', test_loss)
print('Test accuracy:', test_accuracy)

182/182 [==============================] - 0s 937us/step - loss: 0.3179 - accuracy: 0.8653
Test loss: 0.3178878724575043
Test accuracy: 0.8652653098106384

In [9]:
y_pred = model.predict(X_test)
y_pred = np.round(y_pred)

In [10]:
# dataT.to_csv("pred_1.csv")